### ISSUE TITLE
Janus Crash when with FreeSwitch

### ISSUE THREAD

**Issue by liulongqiang1984** [meetecho/janus-gateway#1106]
i got core gdb result, maybe should add protected  （ice_handle->audio_stream && ice_handle->audio_stream->rtp_component）on line 3023 in janus.c file

```
#0  0x0000000000448a73 in janus_plugin_handle_sdp (plugin_session=plugin_session@entry=0x7fb440077fe0, plugin=plugin@entry=
    0x7fb4585e2540 <janus_sip_plugin>, sdp_type=sdp_type@entry=0x7fb44c15ffb0 "answer", sdp=sdp@entry=0x7fb44c1cb560 "v=0\r\no=FreeSWITCH 1512682640 1512682641 IN IP4 47.94.47.96\r\ns=FreeSWITCH\r\nc=IN IP4 47.94.47.96\r\nt=0 0\r\nm=audio 31820 RTP/AVP 0 101\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:101 telephone-event/8000\r\na=fmtp:101 "...) at janus.c:3023
#1  0x000000000044a787 in janus_plugin_push_event (plugin_session=0x7fb440077fe0, plugin=
    0x7fb4585e2540 <janus_sip_plugin>, transaction=0x0, message=0x7fb44c08b320, jsep=0x7fb44c2c3790) at janus.c:2788
#2  0x00007fb4583d1b7f in janus_sip_sofia_callback (event=<optimized out>, status=<optimized out>, phrase=<optimized out>, nua=0x7fb44c404ae0, magic=0x7fb440110950, nh=0x7fb4683130e0, hmagic=0x7fb440110950, sip=0x7fb4543cccf8, tags=0x7fb4540c9030) at plugins/janus_sip.c:3262
#3  0x00007fb4580db7d5 in nua_application_event () at /lib64/libsofia-sip-ua.so.0
#4  0x00007fb45812d982 in su_base_port_execute_msgs () at /lib64/libsofia-sip-ua.so.0
#5  0x00007fb45812df0d in su_base_port_run () at /lib64/libsofia-sip-ua.so.0
#6  0x00007fb4583c8728 in janus_sip_sofia_thread (user_data=0x7fb440110950) at plugins/janus_sip.c:4122
#7  0x00007fb48ef95f20 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#8  0x00007fb48d7ebe25 in start_thread () at /lib64/libpthread.so.0
#9  0x00007fb48d51934d in clone () at /lib64/libc.so.6
```

**Comment by lminiero** [comment]
Is it really so hard reading the guidelines? No inline logs, please!

**Comment by lminiero** [comment]
That said, the info you provided is not enough. It doesn't say what state the handle was in, for instance. Was an answer pushed by the plugin why the WebRTC channel was being destroyed? Was the handle being detached? etc.etc. AddressSanitizer will also tell us more.

**Comment by lminiero** [comment]
Any update with the info we asked for?

**Comment by liulongqiang1984** [comment]
i only crash core file, but i don't know if it helpful?, if need it i can upload website can download it

**Comment by lminiero** [comment]
We made a lot of questions about the scenario you were trying to replicate, and what happened when it crashed... that's something you can answer already. We also asked for an AddressSanitizer (libasan) report: https://janus.conf.meetecho.com/docs/debug

**Comment by lminiero** [comment]
Any update?

**Comment by liulongqiang1984** [comment]
not reopen i closed it

**Comment by MrsZ** [comment]
你已经解决这个问题了吗 哈哈
