### ISSUE TITLE
latest master in fedora - seg fault

### ISSUE THREAD

**Issue by samdulles** [meetecho/janus-gateway#127]
I just installed the latest master version. When starting janus, I get a core dump in fedora. 

(gdb) bt
#0  0x00000030596389f0 in g_hash_table_iter_next () from /lib64/libglib-2.0.so.0
#1  0x000000000040b0d5 in main (argc=<optimized out>, argv=<optimized out>) at janus.c:4017
##   Starting Meetecho Janus (WebRTC Gateway) v0.0.6

Reading configuration from /usr/local/etc/janus/janus.cfg
Checking command line arguments...
[janus.cfg]
    [general]
        configs_folder: /usr/local/etc/janus
        plugins_folder: /usr/local/src/janus-gateway/trunk/plugins
        debug_level: 7
    [webserver]
        base_path: /janus
        threads: unlimited
        http: yes
        port: 8088
        https: no
        ws: yes
        ws_port: 8188
        ws_ssl: no
    [rabbitmq]
        enable: no
        host: localhost
        to_janus: to-janus
        from_janus: from-janus
    [admin]
        admin_base_path: /admin
        admin_threads: unlimited
        admin_http: no
        admin_port: 7088
        admin_https: no
        admin_secret: janusoverlord
    [certificates]
        cert_pem: certs/mycert.pem
        cert_key: certs/mycert.key
    [nat]
        nice_debug: false
        ice_ignore_list: vmnet
Debug/log level is 7
Adding 'vmnet' to the ICE ignore list...
Available interfaces:
        lo:     127.0.0.1
        eth0:   192.241.224.149
Using 192.241.224.149 as local IP...
Initializing ICE stuff (IPv6 candidates disabled)
Enabling libnice debugging...
[WARN] No NICE_DEBUG environment variable set, setting maximum debug
Debugging NICE_DEBUG=all
Using certificates:
        certs/mycert.pem
        certs/mycert.key
Fingerprint of our certificate: C5:5F:DA:7D:84:47:B1:BF:6B:55:16:62:48:31:3E:D3:F1:7B:25:89:92:4A:4B:4D:4D:D9:D5:AF:EA:D8:15:44
Plugins folder: /usr/local/src/janus-gateway/trunk/plugins

(process:886): GLib-CRITICAL **: g_hash_table_iter_init: assertion 'hash_table != NULL' failed

(process:886): GLib-CRITICAL **: g_hash_table_iter_next: assertion 'ri->position < ri->hash_table->size' failed
Using a thread per connection for the HTTP webserver
[FATAL] [janus.c:main:4088:] Couldn't start webserver on port 8088...
[root@webrtc1 trunk]#

**Comment by samdulles** [comment]
i missed to run make install/make config. re-ran make and everything is good.
