### ISSUE TITLE
Janus API request going down janus

### ISSUE THREAD

**Issue by izemize** [meetecho/janus-gateway#1415]
Janus died when sending api request

```

Processing POST data (application/x-www-form-urlencoded) (0 bytes)...
[transports/janus_http.c:janus_http_handler:1266] Done getting payload, we can answer
{"janus":"message","body":{"request":"exists","room":1},"apisecret":"xxx","transaction":"yLhkgIzyRJPy"}
Forwarding request to the core (0x604000009d50)
Got a Janus API request from janus.transport.http (0x604000009d50)
Transport task pool, serving request
[3388966109354534] There's a message for JANUS TextRoom plugin
Creating plugin result...
Attempt to unlock mutex that was not locked

```

```
#0  0x00007f43f60bb067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f43f60bc448 in __GI_abort () at abort.c:89
#2  0x00007f43f7c0872d in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f43e946b63e in janus_textroom_handle_message (handle=0x604000007e90, transaction=0x60200001bfb0 "yLhkgIzyRJPy", message=0x607000009cc0, jsep=0x0) at plugins/janus_textroom.c:1100
#4  0x0000000000488f98 in janus_process_incoming_request (request=0x604000009b10) at janus.c:1327
#5  0x0000000000498b9c in janus_transport_task (data=0x604000009b10, user_data=0x0) at janus.c:2596
#6  0x00007f43f7bebf58 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007f43f7beb5c5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007f43f6439064 in start_thread (arg=0x7f43e6f03700) at pthread_create.c:309
#9  0x00007f43f616e62d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

I hope you look relevant debug info in this logs.

```
New connection on REST API: ::ffff:185.xx.67.xxx
[New Thread 0x7fffe69a7700 (LWP 24572)]
[transports/janus_http.c:janus_http_handler:1150] Got a HTTP POST request on /janus...
[transports/janus_http.c:janus_http_handler:1151]  ... Just parsing headers for now...
[transports/janus_http.c:janus_http_headers:1761] Accept: */*
[transports/janus_http.c:janus_http_headers:1761] Host: xxx.eu:8089
[transports/janus_http.c:janus_http_headers:1761] Connection: close
[transports/janus_http.c:janus_http_headers:1761] Accept-encoding: gzip, deflate
[transports/janus_http.c:janus_http_headers:1761] Content-type: application/x-www-form-urlencoded
[transports/janus_http.c:janus_http_headers:1761] User-agent: EHttpClient
[transports/janus_http.c:janus_http_headers:1761] Content-Length: 76
[transports/janus_http.c:janus_http_handler:1183] Processing HTTP POST request on /janus...
[transports/janus_http.c:janus_http_handler:1236]  ... parsing request...
Processing POST data (application/x-www-form-urlencoded) (76 bytes)...
[transports/janus_http.c:janus_http_handler:1261]   -- Data we have now (76 bytes)
[transports/janus_http.c:janus_http_handler:1183] Processing HTTP POST request on /janus...
[transports/janus_http.c:janus_http_handler:1236]  ... parsing request...
Processing POST data (application/x-www-form-urlencoded) (0 bytes)...
[transports/janus_http.c:janus_http_handler:1266] Done getting payload, we can answer
{"janus":"create","transaction":"IvvY4FkEQxyL","apisecret":"xxx"}
Forwarding request to the core (0x604000009fd0)
Got a Janus API request from janus.transport.http (0x604000009fd0)
Creating new session: 13322729490967; 0x607000006fb0
Session created (13322729490967), create a queue for the long poll
Sending Janus API response to janus.transport.http (0x604000009fd0)
Got a Janus API response to send (0x604000009fd0)
[Thread 0x7fffe69a7700 (LWP 24572) exited]
New connection on REST API: ::ffff:185.xx.67.xxx
[New Thread 0x7fffe61a6700 (LWP 24573)]
[transports/janus_http.c:janus_http_handler:1150] Got a HTTP POST request on /janus/13322729490967...
[transports/janus_http.c:janus_http_handler:1151]  ... Just parsing headers for now...
[transports/janus_http.c:janus_http_headers:1761] Accept: */*
[transports/janus_http.c:janus_http_headers:1761] Host: xxx.eu:8089
[transports/janus_http.c:janus_http_headers:1761] Connection: close
[transports/janus_http.c:janus_http_headers:1761] Accept-encoding: gzip, deflate
[transports/janus_http.c:janus_http_headers:1761] Content-type: application/x-www-form-urlencoded
[transports/janus_http.c:janus_http_headers:1761] User-agent: EHttpClient
[transports/janus_http.c:janus_http_headers:1761] Content-Length: 109
[transports/janus_http.c:janus_http_handler:1183] Processing HTTP POST request on /janus/13322729490967...
[transports/janus_http.c:janus_http_handler:1236]  ... parsing request...
Session: 13322729490967
Processing POST data (application/x-www-form-urlencoded) (109 bytes)...
[transports/janus_http.c:janus_http_handler:1261]   -- Data we have now (109 bytes)
[transports/janus_http.c:janus_http_handler:1183] Processing HTTP POST request on /janus/13322729490967...
[transports/janus_http.c:janus_http_handler:1236]  ... parsing request...
Session: 13322729490967
Processing POST data (application/x-www-form-urlencoded) (0 bytes)...
[transports/janus_http.c:janus_http_handler:1266] Done getting payload, we can answer
{"janus":"attach","plugin":"janus.plugin.textroom","transaction":"pl5s36kDBR~d","apisecret":"xxx"}
Forwarding request to the core (0x604000009e90)
Got a Janus API request from janus.transport.http (0x604000009e90)
Creating new handle in session 13322729490967: 5135300176990439; 0x607000006fb0 0x61200002fec0
Sending Janus API response to janus.transport.http (0x604000009e90)
Got a Janus API response to send (0x604000009e90)
[Thread 0x7fffe61a6700 (LWP 24573) exited]
New connection on REST API: ::ffff:185.51.67.102
[New Thread 0x7fffe69a7700 (LWP 24574)]
[transports/janus_http.c:janus_http_handler:1150] Got a HTTP POST request on /janus/13322729490967/5135300176990439...
[transports/janus_http.c:janus_http_handler:1151]  ... Just parsing headers for now...
[transports/janus_http.c:janus_http_headers:1761] Accept: */*
[transports/janus_http.c:janus_http_headers:1761] Host: deejaytv.eu:8089
[transports/janus_http.c:janus_http_headers:1761] Connection: close
[transports/janus_http.c:janus_http_headers:1761] Accept-encoding: gzip, deflate
[transports/janus_http.c:janus_http_headers:1761] Content-type: application/x-www-form-urlencoded
[transports/janus_http.c:janus_http_headers:1761] User-agent: EHttpClient
[transports/janus_http.c:janus_http_headers:1761] Content-Length: 114
[transports/janus_http.c:janus_http_handler:1183] Processing HTTP POST request on /janus/13322729490967/5135300176990439...
[transports/janus_http.c:janus_http_handler:1236]  ... parsing request...
Session: 13322729490967
Handle: 5135300176990439
Processing POST data (application/x-www-form-urlencoded) (114 bytes)...
[transports/janus_http.c:janus_http_handler:1261]   -- Data we have now (114 bytes)
[transports/janus_http.c:janus_http_handler:1183] Processing HTTP POST request on /janus/13322729490967/5135300176990439...
[transports/janus_http.c:janus_http_handler:1236]  ... parsing request...
Session: 13322729490967
Handle: 5135300176990439
Processing POST data (application/x-www-form-urlencoded) (0 bytes)...
[transports/janus_http.c:janus_http_handler:1266] Done getting payload, we can answer
{"janus":"message","body":{"request":"exists","room":1},"apisecret":"xxx","transaction":"uEmuofrXt3df"}
Forwarding request to the core (0x604000009d50)
Got a Janus API request from janus.transport.http (0x604000009d50)
[New Thread 0x7fffe61a6700 (LWP 24575)]
Transport task pool, serving request
[5135300176990439] There's a message for JANUS TextRoom plugin
Creating plugin result...
Attempt to unlock mutex that was not locked

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe61a6700 (LWP 24575)]
0x00007ffff490f067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.

(gdb) bt
#0  0x00007ffff490f067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff4910448 in __GI_abort () at abort.c:89
#2  0x00007ffff645c72d in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fffe7cbf63e in janus_textroom_handle_message (handle=0x604000007e90, transaction=0x602000000fb0 "uEmuofrXt3df", message=0x607000009cc0, jsep=0x0) at plugins/janus_textroom.c:1100
#4  0x0000000000488f98 in janus_process_incoming_request (request=0x604000009b10) at janus.c:1327
#5  0x0000000000498b9c in janus_transport_task (data=0x604000009b10, user_data=0x0) at janus.c:2596
#6  0x00007ffff643ff58 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff643f5c5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff4c8d064 in start_thread (arg=0x7fffe61a6700) at pthread_create.c:309
#9  0x00007ffff49c262d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

```

**Comment by lminiero** [comment]
Closing as this doesn't respect the guidelines:

> If you want to open an issue, please make sure that:
>
> 1. you actually found a bug: for generic questions, use the [meetecho-janus](http://groups.google.com/d/forum/meetecho-janus) group instead;
> 2. nobody opened the same bug already (do a search);
> 3. the issue wasn't already solved in master;
> 4. you don't paste a huge amount of text in the issue or comments: use a service like [pastebin](http://pastebin.com/) or similar;
> 5. you provide a GDB stacktrace if Janus crashed on you, and/or output from AddressSanitizer or Valgrind (more details available [here](http://janus.conf.meetecho.com/docs/debug.html)).
>
> If so, just remove this text and share your findings!

**Comment by izemize** [comment]
I think, this issue generated by your http-single-thread changes, and you merged in to master whithout comprehensive test. Why can you closing ticket without any question? And how can i add missing info to  this issue? which missing?

**Comment by lminiero** [comment]
I've closed the issue without even reading it because of the huge text inline instead of a pastebin. Sorry, but that's the only way I can get people to read the guidelines.

As a side note, I have *not* merged the HTTP single thread branch: it's still there.
