### ISSUE TITLE
janus crash while set stun server

### ISSUE THREAD

**Issue by jerrylining** [meetecho/janus-gateway#1417]
```
#0  0x00007f5679c30c80 in pthread_mutex_lock () from /usr/lib64/libpthread.so.0
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.26-23.el7.x86_64 glibc-2.17-222.el7.x86_64 jansson-2.11-1.el6.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-19.el7.x86_64 libblkid-2.23.2-52.el7_5.1.x86_64 libcom_err-1.42.9-12.el7_5.x86_64 libcurl-7.29.0-46.el7.x86_64 libffi-3.0.13-18.el7.x86_64 libidn-1.28-4.el7.x86_64 libmount-2.23.2-52.el7_5.1.x86_64 libselinux-2.5-12.el7.x86_64 libssh2-1.4.3-10.el7_2.1.x86_64 libuuid-2.23.2-52.el7_5.1.x86_64 nettle-2.7.1-8.el7.x86_64 nspr-4.13.1-1.0.el7_3.x86_64 nspr-4.19.0-1.el7_5.x86_64 nss-3.28.4-8.el7.x86_64 nss-3.36.0-7.el7_5.x86_64 nss-softokn-freebl-3.28.3-6.el7.x86_64 nss-softokn-freebl-3.36.0-5.el7_5.x86_64 nss-util-3.28.4-3.el7.x86_64 nss-util-3.36.0-1.el7_5.x86_64 openldap-2.4.44-15.el7_5.x86_64 openssl-libs-1.0.2k-12.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007f5679c30c80 in pthread_mutex_lock () from /usr/lib64/libpthread.so.0
#1  0x00007f5677e5eedc in gnutls_system_mutex_lock (priv=<optimized out>)
    at system.c:232
#2  0x00007f5677eeb172 in wrap_nettle_rnd (_ctx=<optimized out>, level=0, 
    data=0x7ffdc9c21a80, datasize=16) at rnd.c:428
#3  0x00007f567b648b5a in stun_agent_init_request (
    agent=agent@entry=0x7ffdc9c21d20, msg=msg@entry=0x7ffdc9c21c60, 
    buffer=buffer@entry=0x7ffdc9c25010 "", buffer_len=buffer_len@entry=1500, 
    m=m@entry=STUN_BINDING) at stunagent.c:386
#4  0x00007f567b646d57 in stun_usage_bind_create (
    agent=agent@entry=0x7ffdc9c21d20, msg=msg@entry=0x7ffdc9c21c60, 
    buffer=buffer@entry=0x7ffdc9c25010 "", buffer_len=buffer_len@entry=1500)
    at usages/bind.c:91
#5  0x000000000042df43 in janus_ice_set_stun_server (
    stun_server=stun_server@entry=0x7e9f20 "stun.voip.eutelia.it", 
    stun_port=stun_port@entry=3478) at ice.c:848
#6  0x000000000040f284 in main (argc=<optimized out>, argv=<optimized out>)
    at janus.c:3740
```

**Comment by jerrylining** [comment]
glib version glib-2.50.3
libnice libnice-0.1.14

**Comment by jerrylining** [comment]
glib version glib-2.50.3
libnice libnice-0.1.14
nettle-3.4

**Comment by lminiero** [comment]
Closing as this doesn't respect the guidelines:

> If you want to open an issue, please make sure that:
>
> 1. you actually found a bug: for generic questions, use the [meetecho-janus](http://groups.google.com/d/forum/meetecho-janus) group instead;
> 2. nobody opened the same bug already (do a search);
> 3. the issue wasn't already solved in master;
> 4. you don't paste a huge amount of text in the issue or comments: use a service like [pastebin](http://pastebin.com/) or similar;
> 5. you provide a GDB stacktrace if Janus crashed on you, and/or output from AddressSanitizer or Valgrind (more details available [here](http://janus.conf.meetecho.com/docs/debug.html)).
>
> If so, just remove this text and share your findings!

**Comment by jerrylining** [comment]
glib version glib-2.50.3
libnice libnice-0.1.14
nettle-3.4
gnutls-3.5.9

**Comment by jerrylining** [comment]
ok, than you

**Comment by lminiero** [comment]
Apologies, this was meant for another issue: the only problem with your issue was that you had pasted inline without using the markdown quote format, which I fixed for you. Reopening.

**Comment by jerrylining** [comment]
When set nat server address. Start janus, segfaults then occurred.

Versions:
 
janus-gateway0.5.0(compiled from https://github.com/meetecho/janus-gateway/commit/fe18b8c35f219f1d09576f62920b11254ff385db)
glib-2.50.3
libnice libnice-0.1.14
nettle-3.4
gnutls-3.5.9
CentOS Linux release 7.5.1804

Backtrace:
```c
#0  0x00007f5679c30c80 in pthread_mutex_lock () from /usr/lib64/libpthread.so.0
#1  0x00007f5677e5eedc in gnutls_system_mutex_lock (priv=<optimized out>)
    at system.c:232
#2  0x00007f5677eeb172 in wrap_nettle_rnd (_ctx=<optimized out>, level=0, 
    data=0x7ffdc9c21a80, datasize=16) at rnd.c:428
#3  0x00007f567b648b5a in stun_agent_init_request (
    agent=agent@entry=0x7ffdc9c21d20, msg=msg@entry=0x7ffdc9c21c60, 
    buffer=buffer@entry=0x7ffdc9c25010 "", buffer_len=buffer_len@entry=1500, 
    m=m@entry=STUN_BINDING) at stunagent.c:386
#4  0x00007f567b646d57 in stun_usage_bind_create (
    agent=agent@entry=0x7ffdc9c21d20, msg=msg@entry=0x7ffdc9c21c60, 
    buffer=buffer@entry=0x7ffdc9c25010 "", buffer_len=buffer_len@entry=1500)
    at usages/bind.c:91
#5  0x000000000042df43 in janus_ice_set_stun_server (
    stun_server=stun_server@entry=0x7e9f20 "stun.voip.eutelia.it", 
    stun_port=stun_port@entry=3478) at ice.c:848
#6  0x000000000040f284 in main (argc=<optimized out>, argv=<optimized out>)
    at janus.c:3740

```

**Comment by lminiero** [comment]
Works fine here. Anyway, your problem seems to be occurring within libnice, so it's not a Janus bug. You should try libnice master. Closing.

**Comment by jerrylining** [comment]
Thank your answering, I will use the master libnice to test it instead.

发自我的 iPhone

**Comment by jerrylining** [comment]
when I switch libnice to master, it works, thank you again :)
