### ISSUE TITLE
Segfault in janus_ice_outgoing_traffic_handle

### ISSUE THREAD

**Issue by danpascu** [meetecho/janus-gateway#1455]
I found this ASAN trace (no core left because of ASAN, so I cannot inspect it further). This is with git revision 6b916658

```
Nov 28 10:34:43 node15 janus[8001]: [ERR] [ice.c:janus_ice_outgoing_traffic_handle:3972] [2652832578174196] ... only sent -1 bytes? (was 1154)
Nov 28 10:34:43 node15 janus[8001]: [ERR] [ice.c:janus_ice_outgoing_traffic_handle:3972] [2652832578174196] ... only sent -1 bytes? (was 1154)
Nov 28 10:35:17 node15 janus[8001]: [WARN] [2659911047686766] Didn't receive audio for more than 1 seconds...
Nov 28 10:35:27 node15 janus[8001]: [WARN] [4335775300784318] Didn't receive audio for more than 1 seconds...
Nov 28 10:35:28 node15 janus[8001]: [WARN] [4335775300784318] Didn't receive video for more than a second...
Nov 28 10:35:30 node15 janus[8001]: [janus.plugin.videoroom-0x6040093132d0] No WebRTC media anymore; 0x612000115cc0 0x60700071adc0
Nov 28 10:35:30 node15 janus[8001]: Detaching handle from JANUS VideoRoom plugin; 0x612000115cc0 0x6040093132d0 0x612000115cc0 0x60700071adc0
Nov 28 10:35:30 node15 janus[8001]: [janus.plugin.videoroom-0x6040093132d0] No WebRTC media anymore; 0x612000115cc0 0x60700071adc0
Nov 28 10:35:30 node15 janus[8001]: [5535051370138712] WebRTC resources freed; 0x612000115cc0 0x60700024f820
Nov 28 10:35:30 node15 janus[8001]: Detaching handle from JANUS VideoRoom plugin; 0x61200036fdc0 0x604003f5dd50 0x61200036fdc0 0x6070003f2da0
Nov 28 10:35:30 node15 janus[8001]: [janus.plugin.videoroom-0x604003f5dd50] No WebRTC media anymore; 0x61200036fdc0 0x6070003f2da0
Nov 28 10:35:30 node15 janus[8001]: [2659911047686766] WebRTC resources freed; 0x61200036fdc0 0x60700024f820
Nov 28 10:35:30 node15 janus[8001]: [2659911047686766] Handle and related resources freed; 0x61200036fdc0 0x60700024f820
Nov 28 10:35:30 node15 janus[8001]: [ERR] [plugins/janus_videoroom.c:janus_videoroom_handler:5266] No such room
Nov 28 10:35:30 node15 janus[8001]: [5535051370138712] Handle and related resources freed; 0x612000115cc0 0x60700024f820
Nov 28 10:35:30 node15 janus[8001]: [janus.plugin.videoroom-0x604008eb29d0] No WebRTC media anymore; 0x612000018940 0x60700025f260
Nov 28 10:35:30 node15 janus[8001]: [2652832578174196] WebRTC resources freed; 0x612000018940 0x6070007a77d0
Nov 28 10:35:30 node15 janus[8001]: Detaching handle from JANUS VideoRoom plugin; 0x612000018940 0x604008eb29d0 0x612000018940 0x60700025f260
Nov 28 10:35:30 node15 janus[8001]: [2652832578174196] Handle and related resources freed; 0x612000018940 0x6070007a77d0
Nov 28 10:35:37 node15 janus[8001]: [WARN] [4335775300784318] Didn't receive video for more than a second...
Nov 28 10:35:37 node15 janus[8001]: AddressSanitizer:DEADLYSIGNAL
Nov 28 10:35:37 node15 janus[8001]: =================================================================
Nov 28 10:35:37 node15 janus[8001]: ==8001==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000018 (pc 0x7f6fc0249f34 bp 0x61d000041df0 sp 0x7f6f94abc060 T7065)
Nov 28 10:35:37 node15 janus[8001]: ==8001==The signal is caused by a READ memory access.
Nov 28 10:35:37 node15 janus[8001]: ==8001==Hint: address points to the zero page.
Nov 28 10:35:38 node15 janus[8001]:     #0 0x7f6fc0249f33 in g_socket_send_message (/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0+0x81f33)
Nov 28 10:35:38 node15 janus[8001]:     #1 0x7f6fc0399ef7  (/usr/lib/x86_64-linux-gnu/libnice.so.10+0x29ef7)
Nov 28 10:35:38 node15 janus[8001]:     #2 0x7f6fc039a162  (/usr/lib/x86_64-linux-gnu/libnice.so.10+0x2a162)
Nov 28 10:35:38 node15 janus[8001]:     #3 0x7f6fc0383190  (/usr/lib/x86_64-linux-gnu/libnice.so.10+0x13190)
Nov 28 10:35:38 node15 janus[8001]:     #4 0x7f6fc038387a in nice_agent_send (/usr/lib/x86_64-linux-gnu/libnice.so.10+0x1387a)
Nov 28 10:35:38 node15 janus[8001]:     #5 0x55bcf4aeaf7e in janus_ice_outgoing_traffic_handle ice.c:3848
Nov 28 10:35:38 node15 janus[8001]:     #6 0x55bcf4af18e6 in janus_ice_outgoing_traffic_dispatch ice.c:360
Nov 28 10:35:38 node15 janus[8001]:     #7 0x7f6fc009dc3d in g_main_context_dispatch (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4dc3d)
Nov 28 10:35:38 node15 janus[8001]:     #8 0x7f6fc009ded7  (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4ded7)
Nov 28 10:35:38 node15 janus[8001]:     #9 0x7f6fc009e1d1 in g_main_loop_run (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4e1d1)
Nov 28 10:35:38 node15 janus[8001]:     #10 0x55bcf4ae55ec in janus_ice_handle_thread ice.c:1056
Nov 28 10:35:38 node15 janus[8001]:     #11 0x7f6fc00c6134  (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x76134)
Nov 28 10:35:38 node15 janus[8001]:     #12 0x7f6fbf64ff29 in start_thread /build/glibc-aYuVJl/glibc-2.27/nptl/pthread_create.c:463
Nov 28 10:35:38 node15 janus[8001]:     #13 0x7f6fbf57fede in __clone (/lib/x86_64-linux-gnu/libc.so.6+0xf7ede)
Nov 28 10:35:38 node15 janus[8001]: AddressSanitizer can not provide additional info.
Nov 28 10:35:38 node15 janus[8001]: SUMMARY: AddressSanitizer: SEGV (/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0+0x81f33) in g_socket_send_message
Nov 28 10:35:38 node15 janus[8001]: Thread T7065 (hloop 433577530) created by T3 here:
Nov 28 10:35:38 node15 janus[8001]:     #0 0x7f6fc0601ef0 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x49ef0)
Nov 28 10:35:38 node15 janus[8001]:     #1 0x7f6fc00e42df  (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x942df)
Nov 28 10:35:38 node15 janus[8001]: Thread T3 created by T0 here:
Nov 28 10:35:38 node15 janus[8001]:     #0 0x7f6fc0601ef0 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x49ef0)
Nov 28 10:35:38 node15 janus[8001]:     #1 0x7f6fc00e42df  (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x942df)
Nov 28 10:35:38 node15 janus[8001]: ==8001==ABORTING

```

**Comment by danpascu** [comment]
No. The room is kept alive as long as there are participants in it. In addition every room is kept for an extra 15 seconds after all participants have left.

**Comment by atoppi** [comment]
Your log line `[ERR] [plugins/janus_videoroom.c:janus_videoroom_handler:5266] No such room`, along with so many WebRTC connections being closed, made me think about that.

**Comment by atoppi** [comment]
@danpascu maybe a higher debugging level (like 5) might help. The crash apparently occurred after 7 seconds of "silence"... something must have been happened to the ICE state or handle if a pointer gets cleared.

**Comment by lminiero** [comment]
Is libnice updated to master?

**Comment by danpascu** [comment]
libnice is version 0.1.14

**Comment by lminiero** [comment]
Please try master as suggested in the README, as they fixed a ton of issues (including a performance bottleneck on high numbers).

**Comment by lminiero** [comment]
@danpascu any update with libnice master?

**Comment by danpascu** [comment]
Sorry, I won't be able to test anything for the next 3 weeks as I'm on vacation until next year.

**Comment by lminiero** [comment]
@danpascu just pinging to check if you managed to get back to this in the meanwhile.

**Comment by amnonbb** [comment]
#1459 
For me it's happened something like three times in last month.
The problem is that occur once a week.
I use libnice 0.1.14.1
I'll try last master and will give feedback here.

**Comment by amnonbb** [comment]
Crashed with same dump. :(
Used latest libnice master.
