### ISSUE TITLE
Invalid RTX payload mapping with enabled rfc4588_rtx

### ISSUE THREAD

**Issue by tharkum** [meetecho/janus-gateway#1469]
I have:
Janus server version 0.6.0 with Janus demo html (Video Call Plugin)
Janus.jcfg
```
media: {
 rfc_4588 = true
}
```

I get the following error during establish connection in Chrome 70 (WIndows10):
`WebRTC error... {"stack":"Error: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. \n at RTCPeerConnection.e.RTCPeerConnection.(anonymous function) [as setRemoteDescription] (https://cdnjs.cloudflare.com/ajax/libs/webrtc-adapter/6.0.3/adapter.min.js:1:46586)\n at streamsDone (https://172.26.123.126/janus/janus.js:1717:14)\n at https://172.26.123.126/janus/janus.js:2238:8"}`

Local SDP: https://pastebin.com/wPDjqZd1
Remote SDP: https://pastebin.com/NbcNqg95

Error happens due invalid RTX payload value (128) for m=video line in remote SDP
Sender: `m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 122 127 121 125 107 108 109 124 120 123 119 114`

Receiver: `m=video 9 UDP/TLS/RTP/SAVPF 96 98 100 102 127 125 108 124 97 99 101 103 128 126 109 104`

```
a=rtpmap:128 rtx/90000
a=fmtp:128 apt=127
```

Seems like Janus server cannot make RTX mapping correctly for codec with payload 127:
Dynamic payload types in range [96 - 127] : https://tools.ietf.org/html/rfc3551#section-6

janus.c (see line 2948):
```
2938 >---if(janus_flags_is_set(&ice_handle->webrtc_flags, JANUS_ICE_HANDLE_WEBRTC_RFC4588_RTX) &&
2939 >--->--->---stream->rtx_payload_types == NULL) {
2940 >--->---/* Make sure we have a list of rtx payload types to generate, if needed */
2941 >--->---janus_sdp_mline *m = janus_sdp_mline_find(parsed_sdp, JANUS_SDP_VIDEO);
2942 >--->---if(m && m->ptypes) {
2943 >--->--->---stream->rtx_payload_types = g_hash_table_new(NULL, NULL);
2944 >--->--->---GList *ptypes = g_list_copy(m->ptypes), *tempP = ptypes;
2945 >--->--->---GList *rtx_ptypes = g_hash_table_get_values(stream->rtx_payload_types);
2946 >--->--->---while(tempP) {
2947 >--->--->--->---int ptype = GPOINTER_TO_INT(tempP->data);
2948 >--->--->--->---int rtx_ptype = ptype+1;
2949 >--->--->--->---while(g_list_find(m->ptypes, GINT_TO_POINTER(rtx_ptype))
2950 >--->--->--->--->--->---|| g_list_find(rtx_ptypes, GINT_TO_POINTER(rtx_ptype))) {
2951 >--->--->--->--->---rtx_ptype++;
2952 >--->--->--->--->---if(rtx_ptype > 127)
2953 >--->--->--->--->--->---rtx_ptype = 96;
2954 >--->--->--->--->---if(rtx_ptype == ptype) {
2955 >--->--->--->--->--->---/* We did a whole round? should never happen... */
2956 >--->--->--->--->--->---rtx_ptype = -1;
2957 >--->--->--->--->--->---break;
2958 >--->--->--->--->---}
2959 >--->--->--->---}
2969 >---}

```

**Comment by lminiero** [comment]
> Error happens due invalid RTX payload value (128) for m=video line in remote SDP

Good catch, thanks, I'll fix that.
