### ISSUE TITLE
Aborted when trying create and destroy room again and again

### ISSUE THREAD

**Issue by xenyou** [meetecho/janus-gateway#185]
Aborted when I try these steps over and over again.

1. create session and handle (videoroom plugin)
2. create room
3. join room (as publisher)
4. destroy room
5. detach handle and destroy session

FYI, I also try it older version but It does not cause this.
So I think recent memory leak fixes could introduce this bug.

Old version I tried:
https://github.com/meetecho/janus-gateway/commit/02aab954b13ddc0f3a2b284a42403912d40dd76f

Error message is here.
```
....
[2478196126] The DTLS handshake has been completed
WebRTC media is now available
[2478196126] Started thread: setup of the SCTP association
[2478196126] Starting thread for SCTP association
[2478196126] Connected to the DataChannel peer
[2478196126] There's a message for JANUS VideoRoom plugin
Detaching handle from JANUS VideoRoom plugin
No WebRTC media anymore
[2478196126] Handle detached (error=0), scheduling destruction
[2478196126] ICE send thread leaving...
Detaching handle from JANUS VideoRoom plugin
[WARN] VideoRoom session already marked as destroyed...
[2478196126] Handle detached (error=0), scheduling destruction
Cleaning up handle 2478196126...
[2478196126] Destroying SCTP association
[2478196126] WebRTC resources freed
[2478196126] Handle and related resources freed
[2478196126] Leaving SCTP association thread
Cleaning up handle 140689773953144...
janus: ../nptl/pthread_mutex_lock.c:116: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
Cleaning up session 3929151247...
Destroying session 3929151247
Aborted (core dumped)
```

And here is the backtrace.
```
ubuntu@ip-172-31-26-56:~$ gdb /opt/janus/bin/janus ./core
(gdb) bt
#0  0x00007ff4ee063cc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ff4ee0670d8 in __GI_abort () at abort.c:89
#2  0x00007ff4ee05cb86 in __assert_fail_base (
    fmt=0x7ff4ee1ad830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=assertion@entry=0x7ff4ee404a5c "mutex->__data.__owner == 0",
    file=file@entry=0x7ff4ee404a28 "../nptl/pthread_mutex_lock.c",
    line=line@entry=116,
    function=function@entry=0x7ff4ee404b60 <__PRETTY_FUNCTION__.8500> "__pthread
_mutex_lock") at assert.c:92
#3  0x00007ff4ee05cc32 in __GI___assert_fail (
    assertion=0x7ff4ee404a5c "mutex->__data.__owner == 0",
    file=0x7ff4ee404a28 "../nptl/pthread_mutex_lock.c", line=116,
    function=0x7ff4ee404b60 <__PRETTY_FUNCTION__.8500> "__pthread_mutex_lock")
    at assert.c:101
#4  0x00007ff4ee3fc52f in __GI___pthread_mutex_lock (mutex=0xfefefefefefefe00)
    at ../nptl/pthread_mutex_lock.c:116
#5  0x000000000041860f in janus_ice_free (handle=0x7ff4e40043e0) at ice.c:694
#6  0x00000000004186a5 in janus_ice_handles_cleanup (user_data=0x7ff4e40043e0)
    at ice.c:188
#7  0x00007ff4f0326703 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ff4f0325ce5 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ff4f0326048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ff4f032630a in g_main_loop_run ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x0000000000413f50 in janus_ice_handles_watchdog (user_data=0x6f26e0)
    at ice.c:230
#12 0x00007ff4f034af05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ff4ee3fa182 in start_thread (arg=0x7ff4e9fae700)
    at pthread_create.c:312
#14 0x00007ff4ee12747d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb)
```

**Comment by lminiero** [comment]
Thanks, I'll look into it.

**Comment by lminiero** [comment]
Apparently the same handle is scheduled to be destroyed twice, which results in a double free and so the abort. I'll try to come up with a fix ASAP.

**Comment by lminiero** [comment]
This should fix it as I'm unable to replicate the issue anymore: feel free to reopen if that's not the case.

**Comment by xenyou** [comment]
Seems that fixed. Thank you for your immediate fix!!
