### ISSUE TITLE
Unable to build js only module

### ISSUE THREAD

**Issue by hjpotter92** [meetecho/janus-gateway#1857]
Trying to build js only module inside a docker container. The file is:

```dockerfile
FROM node:10.17.0-alpine

WORKDIR /opt
ARG JANUS_GATEWAY_VERSION=0.7.5

RUN apk update && apk add wget

RUN wget -q "https://github.com/meetecho/janus-gateway/archive/v${JANUS_GATEWAY_VERSION}.tar.gz" && \
        tar xf "v${JANUS_GATEWAY_VERSION}.tar.gz" && \
        rm -f "v${JANUS_GATEWAY_VERSION}.tar.gz"

WORKDIR /opt/janus-gateway-${JANUS_GATEWAY_VERSION}/npm

RUN npm install && \
        npm run rollup -- -o test.js --f es
```

And this fails with a `ELIFECYCLE` error:

```
module.js → test.js...
[!] Error: Unexpected token
module.js (310:11)
308:       try {
309:         element.srcObject = stream;
310:       } catch {
                   ^
311:         try {
312:           element.src = URL.createObjectURL(stream);

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! janus@ `rollup -c rollup.config.js "-o" "test.js" "--f" "es"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the janus@ rollup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

The verbose log output:
```
7 verbose lifecycle janus@~rollup: unsafe-perm in lifecycle true
8 verbose lifecycle janus@~rollup: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/janus-gateway-0.7.5/npm/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle janus@~rollup: CWD: /opt/janus-gateway-0.7.5/npm
10 silly lifecycle janus@~rollup: Args: [ '-c', 'rollup -c rollup.config.js "-o" "test.js" "--f" "es"' ]
11 silly lifecycle janus@~rollup: Returned: code: 1  signal: null
12 info lifecycle janus@~rollup: Failed to exec rollup script
13 verbose stack Error: janus@ rollup: `rollup -c rollup.config.js "-o" "test.js" "--f" "es"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

**Comment by lminiero** [comment]
I don't know how that thing works, but I'm pretty sure it was solved in #1848. Closing.

**Comment by hjpotter92** [comment]
Ah, I am not building from master, instead doing so from the github releases. The most recent release being 0.7.5

**Comment by lminiero** [comment]
Please check if master fixes the js building issue. If so, then the next tagged release should work using the script you have.

**Comment by hjpotter92** [comment]
Yes, changing the script to build from master indeed works. Thanks
