### ISSUE TITLE
Empty string audio recording path results in segfault

### ISSUE THREAD

**Issue by ptsneves** [meetecho/janus-gateway#1907]
When i send a request to the streaming plugin to start the request with empty audio path there is segfault in janus streaming plugin.

I am on Janus 0.6.1. I am running janus from ubuntu.
```

Thread 16 "pool" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fc1837fe700 (LWP 233)]
__strstr_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S:40
40	../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  0x00007fc1b7f9098d in __strstr_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S:40
#1  0x00007fc1b4154871 in janus_streaming_handle_message (handle=<optimized out>, transaction=0x7fc17c003950 "1aa2c5fd-ccb6-4af7-9c41-52e4312c2cfc", message=0x7fc170002a70, jsep=0x0)
    at plugins/janus_streaming.c:3291
#2  0x00005583c702e819 in janus_process_incoming_request (request=0x7fc17c004550) at janus.c:1342
#3  0x00005583c703403d in janus_transport_task (data=0x7fc17c004550, user_data=<optimized out>) at janus.c:2644
#4  0x00007fc1b8843243 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fc1b884287d in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007fc1b80cd182 in start_thread (arg=<optimized out>) at pthread_create.c:486
#7  0x00007fc1b7ff4b1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
My Mountpoint is the following
```
{
  "janus": "message",
  "body": {
    "id": 6,
    "type": "rtp",
    "audio": false,
    "audioport": 0,
    "audiopt": 0,
    "video": true,
    "videoport": 6626,
    "videopt": 100,
    "videortpmap": "VP8/90000",
    "request": "create",
    "description": "000000000000000000",
    "admin_key": "IY03E0dwBWK8p7jfBZxN"
  },
  "transaction": "1aa2c5fd-ccb6-4af7-9c41-52e4312c2cfc"
}
```

```
{
  "janus": "message",
  "body": {
    "request": "recording",
    "action": "start",
    "audio": "",
    "video": "/tmp//1577487899119",
    "data": "",
    "id": 6,
    "admin_key": "MyKey"
  },
  "transaction": "534a87b3-0f65-4b56-a223-199c730b49ee"
}
```

Maybe it has to do with the fact my mountpoint has audio disabled. If my recording message has no audio field everything works fine.

**Comment by lminiero** [comment]
Thanks for the heads up, I'll have a look at this tomorrow when I'm back at the office.

**Comment by lminiero** [comment]
Not crashing for me. Just noticed you mentioned 0.6.1, though, which is old: I don't debug older versions. Please update to master, and let us know if you can replicate there too: if not, we fixed it already.

**Comment by lminiero** [comment]
Pretty sure this was fixed, since when I use the same exact messages you use, I get this on the logs:

```
[ERR] [plugins/janus_streaming.c:janus_streaming_process_synchronous_request:3479] [mp-6] Audio RTP map is uninitialized
[ERR] [record.c:janus_recorder_create:83] Missing codec information
[ERR] [plugins/janus_streaming.c:janus_streaming_process_synchronous_request:3491] [mp-6] Error starting recorder for audio
```

Closing.
