### ISSUE TITLE
janus crash

### ISSUE THREAD

**Issue by ubonass** [meetecho/janus-gateway#2315]
Dear
   i using janus branch v0.10.3
   when i using audio bridge function, the operation is flow
   1.firstly, when i join the audio bridge room 
   2.then leave the room
   3.then repeat steps 1 and 2 (don't leave the room at last )
   4.then i kill the client process(using android client),it will lead to janus crash and the log file is flow
[80440982380241]  Transport: UDP
[80440982380241] Queueing candidate 0x7fffa000ba90
[80440982380241] Processing candidate 0x7fffa000ba90
[80440982380241] 1 remote candidate added
[80440982380241] Component state changed for component 1 in stream 1: 4 (ready)
[WSS-0x7fffb0000c80] WS connection down, closing
[WSS-0x7fffb0000c80] Destroying WebSocket client
A janus.transport.websockets transport instance has gone away (0x7fffb00043b0)
  -- Session 7450875506811642 will be over if not reclaimed
  -- Marking Session 7450875506811642 as over
Destroying session 7450875506811642; 0x7fffa0001b60
[80440982380241] Hanging up PeerConnection because of a Detach
Detaching handle from JANUS AudioBridge plugin; 0x7fffa0005830 0x7fffa0003da0 0x7fffa0005830 0x7fffa0001af0
[80440982380241] Handle detached, scheduling destruction
[WSS-0x7fffb0000c80]   -- closed
[80440982380241] Telling the plugin about the hangup (JANUS AudioBridge plugin)
[janus.plugin.audiobridge-0x7fffa0003da0] No WebRTC media anymore
No WebRTC media anymore
[80440982380241] WebRTC resources freed; 0x7fffa0005830 0x7fffa0001b60
[80440982380241] Telling the plugin about the handle detach (JANUS AudioBridge plugin)
Removing AudioBridge session...
No WebRTC media anymore
[80440982380241] Sending event to transport...; 0x7fffa0005830

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffa9582700 (LWP 10075)]
0x00007ffff508ad1f in __strlen_sse42 () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.26-23.el7.x86_64 glib2-2.56.1-5.el7.x86_64 glibc-2.17-307.el7.1.x86_64 gmp-6.0.0-15.el7.x86_64 jansson-2.10-1.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-46.el7.x86_64 libblkid-2.23.2-63.el7.x86_64 libcom_err-1.42.9-17.el7.x86_64 libconfig-1.4.9-5.el7.x86_64 libcurl-7.29.0-57.el7.x86_64 libffi-3.0.13-19.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libidn-1.28-4.el7.x86_64 libidn2-2.3.0-1.el7.x86_64 libmount-2.23.2-63.el7.x86_64 libogg-1.3.0-7.el7.x86_64 libselinux-2.5-15.el7.x86_64 libssh2-1.8.0-3.el7.x86_64 libtasn1-4.10-1.el7.x86_64 libunistring-0.9.3-9.el7.x86_64 libuuid-2.23.2-63.el7.x86_64 libuv-1.38.0-2.el7.x86_64 nspr-4.21.0-1.el7.x86_64 nss-3.44.0-7.el7_7.x86_64 nss-softokn-freebl-3.44.0-8.el7_7.x86_64 nss-util-3.44.0-4.el7_7.x86_64 openldap-2.4.44-21.el7_6.x86_64 openssl-libs-1.0.2k-19.el7.x86_64 opus-1.0.2-6.el7.x86_64 p11-kit-0.23.5-3.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffa9582700 (LWP 6068)]
0x00007ffff508ad1f in __strlen_sse42 () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.26-23.el7.x86_64 glib2-2.56.1-5.el7.x86_64 glibc-2.17-307.el7.1.x86_64 gmp-6.0.0-15.el7.x86_64 jansson-2.10-1.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-46.el7.x86_64 libblkid-2.23.2-63.el7.x86_64 libcom_err-1.42.9-17.el7.x86_64 libconfig-1.4.9-5.el7.x86_64 libcurl-7.29.0-57.el7.x86_64 libffi-3.0.13-19.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libidn-1.28-4.el7.x86_64 libidn2-2.3.0-1.el7.x86_64 libmount-2.23.2-63.el7.x86_64 libogg-1.3.0-7.el7.x86_64 libselinux-2.5-15.el7.x86_64 libssh2-1.8.0-3.el7.x86_64 libtasn1-4.10-1.el7.x86_64 libunistring-0.9.3-9.el7.x86_64 libuuid-2.23.2-63.el7.x86_64 libuv-1.38.0-2.el7.x86_64 nspr-4.21.0-1.el7.x86_64 nss-3.44.0-7.el7_7.x86_64 nss-softokn-freebl-3.44.0-8.el7_7.x86_64 nss-util-3.44.0-4.el7_7.x86_64 openldap-2.4.44-21.el7_6.x86_64 openssl-libs-1.0.2k-19.el7.x86_64 opus-1.0.2-6.el7.x86_64 p11-kit-0.23.5-3.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) 
(gdb) 
(gdb) bt
#0  0x00007ffff508ad1f in __strlen_sse42 () at /lib64/libc.so.6
#1  0x00007ffff6a6a5de in json_string () at /lib64/libjansson.so.4
#2  0x000000000042d1ee in janus_events_notify_handlers (type=type@entry=2, subtype=subtype@entry=0, session_id=<optimized out>) at events.c:186
#3  0x0000000000447416 in janus_ice_outgoing_traffic_handle (handle=0x7fffa0005830, pkt=<optimized out>) at ice.c:4155
#4  0x000000000044a164 in janus_ice_outgoing_traffic_dispatch (source=0x7fffa0001db0, callback=<optimized out>, user_data=<optimized out>) at ice.c:376
#5  0x00007ffff6cbb099 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#6  0x00007ffff6cbb3f8 in g_main_context_iterate.isra.19 () at /lib64/libglib-2.0.so.0
#7  0x00007ffff6cbb6ca in g_main_loop_run () at /lib64/libglib-2.0.so.0
#8  0x000000000043bd60 in janus_ice_handle_thread (data=0x7fffa0005830) at ice.c:1165
#9  0x00007ffff6ce2540 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#10 0x00007ffff5319ea5 in start_thread () at /lib64/libpthread.so.0
#11 0x00007ffff50428dd in clone () at /lib64/libc.so.6
(gdb) 

(gdb) bt full
#0  0x00007ffff508ad1f in __strlen_sse42 () at /lib64/libc.so.6
#1  0x00007ffff6a6a5de in json_string () at /lib64/libjansson.so.4
#2  0x000000000042d1ee in janus_events_notify_handlers (type=type@entry=2, subtype=subtype@entry=0, session_id=<optimized out>) at events.c:186
        opaque_id = 0x0
        token = <optimized out>
        handle_id = <optimized out>
        name = <optimized out>
        plugin = <optimized out>
        args = {{gp_offset = 48, fp_offset = 0, overflow_arg_area = 0x7fffa9581980, reg_save_area = 0x7fffa9581910}}
        event = 0x7fff94020830
        body = 0x7fff94021f40
#3  0x0000000000447416 in janus_ice_outgoing_traffic_handle (handle=0x7fffa0005830, pkt=<optimized out>) at ice.c:4155
        plugin = 0x7fffbffff540 <janus_audiobridge_plugin>
        event = <optimized out>
        session = 0x7fffa0001b60
        stream = <optimized out>
        component = <optimized out>
        __FUNCTION__ = "janus_ice_outgoing_traffic_handle"
        age = <optimized out>
#4  0x000000000044a164 in janus_ice_outgoing_traffic_dispatch (source=0x7fffa0001db0, callback=<optimized out>, user_data=<optimized out>) at ice.c:376
        t = 0x7fffa0001db0
        ret = 1
        pkt = <optimized out>
#5  0x00007ffff6cbb099 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#6  0x00007ffff6cbb3f8 in g_main_context_iterate.isra.19 () at /lib64/libglib-2.0.so.0
#7  0x00007ffff6cbb6ca in g_main_loop_run () at /lib64/libglib-2.0.so.0
#8  0x000000000043bd60 in janus_ice_handle_thread (data=0x7fffa0005830) at ice.c:1165
        handle = 0x7fffa0005830
        __FUNCTION__ = "janus_ice_handle_thread"
#9  0x00007ffff6ce2540 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#10 0x00007ffff5319ea5 in start_thread () at /lib64/libpthread.so.0
#11 0x00007ffff50428dd in clone () at /lib64/libc.so.6
(gdb)

**Comment by groupboard** [comment]
You need to test in the latest master.
