### ISSUE TITLE
Crash in plugins/janus_sip.c

### ISSUE THREAD

**Issue by jsharpconv** [meetecho/janus-gateway#2545]
Working with janus-0.7.4.

```
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fa0b7595c74 in raise () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f9901ffb700 (LWP 9094))]
(gdb) bt
#0  0x00007fa0b7595c74 in raise () from /lib64/libc.so.6
#1  0x00007fa0b7597a69 in abort () from /lib64/libc.so.6
#2  0x00007fa0b75da12c in ?? () from /lib64/libc.so.6
#3  0x00007fa0b75e22bd in ?? () from /lib64/libc.so.6
#4  0x00007fa0b75e2bce in ?? () from /lib64/libc.so.6
#5  0x00007fa0b419dbdc in janus_sip_media_reset (session=0x7fa094027680) at plugins/janus_sip.c:1098
#6  janus_sip_media_cleanup (session=session@entry=0x7fa094027680) at plugins/janus_sip.c:4634
#7  0x00007fa0b41a3d88 in janus_sip_relay_thread (data=0x7fa094027680) at plugins/janus_sip.c:4964
#8  0x00007fa0b8e84e28 in ?? () from /usr/lib64/libglib-2.0.so.0
#9  0x00007fa0b7927a83 in start_thread () from /lib64/libpthread.so.0
#10 0x00007fa0b765e6af in clone () from /lib64/libc.so.6

1098		g_free(session->media.remote_audio_ip);

(gdb) print session->media
$1 = {remote_audio_ip = 0x0, remote_video_ip = 0x0, earlymedia = 0, update = 0, autoaccept_reinvites = 1, ready = 0, require_srtp = 0, has_srtp_local_audio = 0, has_srtp_local_video = 0, has_srtp_remote_audio = 0,
  has_srtp_remote_video = 0, srtp_profile = 0, on_hold = 0, has_audio = 0, audio_rtp_fd = -1, audio_rtcp_fd = -1, local_audio_rtp_port = 0, remote_audio_rtp_port = 0, local_audio_rtcp_port = 0, remote_audio_rtcp_port = 0, audio_ssrc = 0,
  audio_ssrc_peer = 0, audio_pt = -1, audio_pt_name = 0x0, audio_srtp_in = 0x0, audio_srtp_out = 0x0, audio_remote_policy = {ssrc = {type = ssrc_any_inbound, value = 0}, rtp = {cipher_type = 0, cipher_key_len = 0, auth_type = 0,
      auth_key_len = 0, auth_tag_len = 0, sec_serv = sec_serv_none}, rtcp = {cipher_type = 0, cipher_key_len = 0, auth_type = 0, auth_key_len = 0, auth_tag_len = 0, sec_serv = sec_serv_none}, key = 0x0, ekt = 0x0, window_size = 0,
    allow_repeat_tx = 0, next = 0x0}, audio_local_policy = {ssrc = {type = ssrc_any_inbound, value = 0}, rtp = {cipher_type = 0, cipher_key_len = 0, auth_type = 0, auth_key_len = 0, auth_tag_len = 0, sec_serv = sec_serv_none}, rtcp = {
      cipher_type = 0, cipher_key_len = 0, auth_type = 0, auth_key_len = 0, auth_tag_len = 0, sec_serv = sec_serv_none}, key = 0x0, ekt = 0x0, window_size = 0, allow_repeat_tx = 0, next = 0x0}, audio_send = 1,
  pre_hold_audio_dir = JANUS_SDP_DEFAULT, has_video = 0, video_rtp_fd = -1, video_rtcp_fd = -1, local_video_rtp_port = 0, remote_video_rtp_port = 0, local_video_rtcp_port = 0, remote_video_rtcp_port = 0, video_ssrc = 0,
  video_ssrc_peer = 0, simulcast_ssrc = 0, video_pt = -1, video_pt_name = 0x0, video_srtp_in = 0x0, video_srtp_out = 0x0, video_remote_policy = {ssrc = {type = ssrc_any_inbound, value = 0}, rtp = {cipher_type = 0, cipher_key_len = 0,
      auth_type = 0, auth_key_len = 0, auth_tag_len = 0, sec_serv = sec_serv_none}, rtcp = {cipher_type = 0, cipher_key_len = 0, auth_type = 0, auth_key_len = 0, auth_tag_len = 0, sec_serv = sec_serv_none}, key = 0x0, ekt = 0x0,
    window_size = 0, allow_repeat_tx = 0, next = 0x0}, video_local_policy = {ssrc = {type = ssrc_any_inbound, value = 0}, rtp = {cipher_type = 0, cipher_key_len = 0, auth_type = 0, auth_key_len = 0, auth_tag_len = 0,
      sec_serv = sec_serv_none}, rtcp = {cipher_type = 0, cipher_key_len = 0, auth_type = 0, auth_key_len = 0, auth_tag_len = 0, sec_serv = sec_serv_none}, key = 0x0, ekt = 0x0, window_size = 0, allow_repeat_tx = 0, next = 0x0},
  video_send = 1, pre_hold_video_dir = JANUS_SDP_DEFAULT, context = {a_last_ssrc = 0, a_last_ts = 0, a_base_ts = 0, a_base_ts_prev = 0, a_prev_ts = 0, a_target_ts = 0, a_start_ts = 0, v_last_ssrc = 0, v_last_ts = 0, v_base_ts = 0,
    v_base_ts_prev = 0, v_prev_ts = 0, v_target_ts = 0, v_start_ts = 0, a_last_seq = 0, a_prev_seq = 0, a_base_seq = 0, a_base_seq_prev = 0, v_last_seq = 0, v_prev_seq = 0, v_base_seq = 0, v_base_seq_prev = 0, a_seq_reset = 0,
    a_new_ssrc = 0, v_seq_reset = 0, v_new_ssrc = 0, a_seq_offset = 0, v_seq_offset = 0, a_prev_delay = 0, a_active_delay = 0, a_ts_offset = 0, v_prev_delay = 0, v_active_delay = 0, v_ts_offset = 0, a_last_time = 0, a_reference_time = 0,
    a_start_time = 0, a_evaluating_start_time = 0, v_last_time = 0, v_reference_time = 0, v_start_time = 0, v_evaluating_start_time = 0}, pipefd = {-1, -1}, updated = 0}

```

**Comment by lminiero** [comment]
0.7.4 is really old, please try master.
