### ISSUE TITLE
janus coredump at plugins/janus_videoroom.c:2725

### ISSUE THREAD

**Issue by lm123** [meetecho/janus-gateway#2698]
Janus (v0.11.3) coredumps at plugins/janus_videoroom.c:2725, the backtrack is as following:

```
(gdb) bt
#0  0x0000000000000040 in ?? ()
#1  0x00007f7aa03214c4 in janus_videoroom_leave_or_unpublish (
    participant=participant@entry=0x7f7a6c025e50,
    is_leaving=is_leaving@entry=0, kicked=kicked@entry=0)
    at plugins/janus_videoroom.c:2725
#2  0x00007f7aa0321c09 in janus_videoroom_hangup_media_internal (
    session_data=session_data@entry=0x7f7a80022680)
    at plugins/janus_videoroom.c:5870
#3  0x00007f7aa0321fe7 in janus_videoroom_hangup_media (handle=<optimized out>)
    at plugins/janus_videoroom.c:5772
#4  0x00007f7aa033bcba in janus_videoroom_handler (data=<optimized out>)
    at plugins/janus_videoroom.c:6895
#5  0x00007f7ac3fd6d25 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007f7ac26586ba in start_thread (arg=0x7f7a9b7fe700)
    at pthread_create.c:333
#7  0x00007f7ac238e51d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

(gdb) f 1
#1  0x00007f7aa03214c4 in janus_videoroom_leave_or_unpublish (
    participant=participant@entry=0x7f7a6c025e50,
    is_leaving=is_leaving@entry=0, kicked=kicked@entry=0)
    at plugins/janus_videoroom.c:2725
warning: Source file is more recent than executable.
2725                    janus_refcount_decrease(&room->ref);
(gdb) p room->ref
$1 = {count = 0, free = 0x40}
```

**Comment by lminiero** [comment]
```
warning: Source file is more recent than executable.
```

Are you sure you're using a recently compiled version of Janus? This warning seems to suggest the code is more recent than the executable and shared objects.

**Comment by lm123** [comment]
Yes.

**Comment by lminiero** [comment]
Please share a libasan trace instead: https://janus-legacy.conf.meetecho.com/docs/debug.html

**Comment by lminiero** [comment]
@lm123 any update on the libasan trace we asked for?

**Comment by lminiero** [comment]
Closing for lack of feedback.
