### ISSUE TITLE
[Segfault] janus_dtls_bio_filter_ctrl not thread safety

### ISSUE THREAD

**Issue by jing3018** [meetecho/janus-gateway#308]
```
#0  janus_dtls_bio_filter_ctrl (bio=<optimized out>, cmd=<optimized out>, num=<optimized out>, ptr=<optimized out>) at dtls-bio.c:130
#1  0x00000000004baa5e in BIO_ctrl (bio=0x7f8ae0002980, cmd=10, larg=0, parg=0x0) at /root/work/boringssl/crypto/bio/bio.c:231
#2  0x00000000004bae2f in BIO_pending (bio=0x7f8ae0002980) at /root/work/boringssl/crypto/bio/bio.c:349
#3  0x00000000004bae49 in BIO_ctrl_pending (bio=0x7f8ae0002980) at /root/work/boringssl/crypto/bio/bio.c:353
#4  0x0000000000417aa1 in janus_dtls_fd_bridge (dtls=dtls@entry=0x7f8ae0001560) at dtls.c:606
#5  0x0000000000418584 in janus_dtls_srtp_incoming_msg (dtls=0x7f8ae0001560, buf=buf@entry=0x7f8b2ffeeb40 "\027\376\377", len=len@entry=1325) at dtls.c:307
#6  0x0000000000429dfc in janus_ice_cb_nice_recv (agent=<optimized out>, stream_id=<optimized out>, component_id=1, len=1325, buf=0x7f8b2ffeeb40 "\027\376\377",
    ice=0x7f8b30019230) at ice.c:1574
```
in gdb 

```
(gdb) p filter
$1 = (janus_dtls_bio_filter *) 0x7f8ae00029e0
(gdb) p *filter
$2 = {packets = 0x0, mutex = {__data = {__lock = 2, __count = 0, __owner = 30884, __nusers = 1, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}},
    __size = "\002\000\000\000\000\000\000\000\244x\000\000\001", '\000' <repeats 26 times>, __align = 2}}
(gdb) l 124
119         case BIO_CTRL_WPENDING:
120             return 0L;
121         case BIO_CTRL_PENDING: {
122             /* We only advertize one packet at a time, as they may be fragmented */
123             janus_dtls_bio_filter *filter = (janus_dtls_bio_filter *)bio->ptr;
124             if(filter == NULL || g_list_length(filter->packets) == 0)
125                 return 0;
126             janus_mutex_lock(&filter->mutex);
127             /* Get the first packet that hasn't been read yet */
128             GList *first = g_list_first(filter->packets);
129            filter->packets = g_list_remove_link(filter->packets, first);
130            int pending = GPOINTER_TO_INT(first->data);
(gdb) p filter->packets
$3 = 0x0
```

1. multi thread check in line 124,  when `g_list_length(filter->packets) > 0` , then all those thread will go to line 126 .
2. when some thread get the lock and `g_list_length(filter->packets) == 0` , then crashed in line 130.

my solution 
```
--- a/dtls-bio.c
+++ b/dtls-bio.c
@@ -124,6 +124,11 @@ long janus_dtls_bio_filter_ctrl(BIO *bio, int cmd, long num, void *ptr) {
                        if(filter == NULL || g_list_length(filter->packets) == 0)
                                return 0;
                        janus_mutex_lock(&filter->mutex);
+                       /* crash in MT , FIXME */
+                       if(g_list_length(filter->packets) == 0) {
+                               janus_mutex_unlock(&filter->mutex);
+                               return 0;
+                       }
                        /* Get the first packet that hasn't been read yet */
                        GList *first = g_list_first(filter->packets);
                        filter->packets = g_list_remove_link(filter->packets, first);
```

**Comment by lminiero** [comment]
Makes sense to add a lock before checking for the packets, I'll fix this in the next commit.
