### ISSUE TITLE
segfault when calling relay_rtp()

### ISSUE THREAD

**Issue by mikesi** [meetecho/janus-gateway#601]
[7542722631788892] The DTLS handshake has been completed
[New Thread 0x7fffb67fc700 (LWP 13956)]
[Thread 0x7fffb67fc700 (LWP 13956) exited]
[New Thread 0x7fffb5ffb700 (LWP 13957)]
relay...[Thread 0x7fffb5ffb700 (LWP 13957) exited]

[Switching to Thread 0x7fffc5f3a700 (LWP 13897)]
0x000000000044d2bb in janus_flags_is_set (flags=flags@entry=0x2d3d6f0a0d303d9e, flag=flag@entry=8) at utils.c:118
118    			return (bit != 0);
(gdb) bt
#0  0x000000000044d2bb in janus_flags_is_set (flags=flags@entry=0x2d3d6f0a0d303d9e, flag=flag@entry=8) at utils.c:118
#1  0x00000000004323a3 in janus_plugin_relay_rtp (plugin_session=<optimized out>, video=1,
    buf=0x7fffc5f29ad0 "\200dim\273\262\200\377\355v\264\330\220\200\350\300\021,", len=985) at janus.c:2879

This happens if i want to relay to a connected peer which is a receiver.
Maybe I did something wrong?

**Comment by mikesi** [comment]
Nevermind a typo for the handle ptr ...
